### ISSUE TITLE
Eror

### ISSUE THREAD

**Issue by NdaruAjaa** [JavierLeon9966/BlockLagFix#12]
PocketMine-MP version: 4.20.0 [Protocol 582]
Git commit: 54ae4d0ea2429bfb020aa1fae444c5ac9e3dcafb
PHP version: 8.0.27
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: BlockLagFix

Error: Class "muqsit\simplepackethandler\SimplePacketHandler" not found
File: plugins/BlockLagFix-master/src/JavierLeon9966/BlockLagFix/BlockLagFix
Line: 49
Type: Error
Backtrace:
#0 pmsrc/src/plugin/PluginBase(118): JavierLeon9966\BlockLagFix\BlockLagFix->onEnable()
#1 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
#2 pmsrc/src/Server(1395): pocketmine\plugin\PluginManager->enablePlugin(object JavierLeon9966\BlockLagFix\BlockLagFix#143275)
#3 pmsrc/src/Server(1030): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#21936)
#4 pmsrc/src/PocketMine(339): pocketmine\Server->__construct(object BaseClassLoader#5, object pocketmine\utils\MainLogger#2, string[16] /home/container/, string[24] /home/container/plugins/)
#5 pmsrc/src/PocketMine(362): pocketmine\server()
#6 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

**Comment by Superomarking** [comment]
The plugin still hasn't been supported for 4.20

**Comment by NdaruAjaa** [comment]
hmm okay

**Comment by JavierLeon9966** [comment]
That isn't the problem, the problem is you're trying to download BlockLagFix from here without injecting the dependencies first. I recommend you download it from poggit: https://poggit.pmmp.io/p/BlockLagFix/1.11.0
