### ISSUE TITLE
Crash related to ender chest (?)

### ISSUE THREAD

**Issue by Studgi** [JavierLeon9966/BlockLagFix#14]
factions-main-1  | [21:19:26.296] [Server thread/CRITICAL]: ArgumentCountError: "Too few arguments to function pocketmine\block\tile\Spawnable::getSerializedSpawnCompound(), 0 passed in /data/plugins/BlockLagFix/src/JavierLeon9966/BlockLagFix/BlockLagFix.php on line 103 and exactly 1 expected" (EXCEPTION) in "pmsrc/src/block/tile/Spawnable" at line 81
factions-main-1  | --- Stack trace ---
factions-main-1  |   #0 plugins/BlockLagFix/src/JavierLeon9966/BlockLagFix/BlockLagFix(103): pocketmine\block\tile\Spawnable->getSerializedSpawnCompound()
factions-main-1  |   #1 plugins/BlockLagFix/src/JavierLeon9966/BlockLagFix/BlockLagFix(110): JavierLeon9966\BlockLagFix\BlockLagFix->JavierLeon9966\BlockLagFix\{closure}(object pocketmine\block\EnderChest#95560)
factions-main-1  |   #2 pmsrc/src/event/RegisteredListener(61): JavierLeon9966\BlockLagFix\BlockLagFix->JavierLeon9966\BlockLagFix\{closure}(object pocketmine\event\player\PlayerInteractEvent#113919)
factions-main-1  |   #3 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerInteractEvent#113919)
factions-main-1  |   #4 pmsrc/src/world/World(2154): pocketmine\event\Event->call()
factions-main-1  |   #5 pmsrc/src/player/Player(1817): pocketmine\world\World->useItemOn(object pocketmine\math\Vector3#115799, object pocketmine\item\ItemBlock#185046, int 1, object pocketmine\math\Vector3#113902, object core\player\MMCPlayer#192372, true, array[0])
factions-main-1  |   #6 pmsrc/src/network/mcpe/handler/InGamePacketHandler(494): pocketmine\player\Player->interactBlock(object pocketmine\math\Vector3#115799, int 1, object pocketmine\math\Vector3#85801)
factions-main-1  |   #7 pmsrc/src/network/mcpe/handler/InGamePacketHandler(347): pocketmine\network\mcpe\handler\InGamePacketHandler->handleUseItemTransaction(object pocketmine\network\mcpe\protocol\types\inventory\UseItemTransactionData#78347)
factions-main-1  |   #8 pmsrc/vendor/nethergamesmc/bedrock-protocol/src/InventoryTransactionPacket(94): pocketmine\network\mcpe\handler\InGamePacketHandler->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#85802)
factions-main-1  |   #9 pmsrc/src/network/mcpe/NetworkSession(512): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#101730)
factions-main-1  |   #10 pmsrc/src/network/mcpe/NetworkSession(455): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#85802, string[62] ..................@..................R..`...r./...,?...?..c?.`)
factions-main-1  |   #11 pmsrc/src/network/mcpe/raklib/RakLibInterface(218): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[87] .Sa...x.......v2..0..u..........LL.9....N.a.b.........9X4M.0...{...{..d.3.. ..@%)
factions-main-1  |   #12 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[96] ....sI].d!...M..G.pD..B..;.).x.%.......S....~o(1...........V, .I.n*.Ny.....\1.i.)
factions-main-1  |   #13 pmsrc/src/network/mcpe/raklib/RakLibInterface(110): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#177032)
factions-main-1  |   #14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
factions-main-1  |   #15 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
factions-main-1  |   #16 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
factions-main-1  |   #17 pmsrc/src/Server(1703): pocketmine\snooze\SleeperHandler->sleepUntil(float 1693257566.3027)
factions-main-1  |   #18 pmsrc/src/Server(1076): pocketmine\Server->tickProcessor()
factions-main-1  |   #19 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[6] /data/, string[14] /data/plugins/)
factions-main-1  |   #20 pmsrc/src/PocketMine(357): pocketmine\server()
factions-main-1  |   #21 pmsrc(11): require(string[50] phar:///data/PocketMine-MP.phar/src/PocketMine.php)
factions-main-1  | --- End of exception information ---

**Comment by b1zeyofficial** [comment]
same problem with shulker @JavierLeon9966

**Comment by JavierLeon9966** [comment]
This plugin is only meant for vanilla PocketMine-MP, not forks like NetherGames
