### ISSUE TITLE
Got some error :D

### ISSUE THREAD

**Issue by DerCooleVonDem** [JavierLeon9966/BlockLagFix#2]
I hope i can help with this stack:

[06:38:10.149] [Server thread/CRITICAL]: Error: "Class "JavierLeon9966\BlockLagFix\libs\muqsit\simplepackethandler\SimplePacketHandler" not found" (EXCEPTION) in "plugins/BlockLagFix.phar/src/BlockLagFix" at line 27
--- Stack trace ---
  #0 pmsrc/src/plugin/PluginBase(137): JavierLeon9966\BlockLagFix\BlockLagFix->onEnable()
  #1 pmsrc/src/plugin/PluginManager(438): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #2 pmsrc/src/Server(1371): pocketmine\plugin\PluginManager->enablePlugin(object JavierLeon9966\BlockLagFix\BlockLagFix#23485)
  #3 pmsrc/src/Server(999): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#23439)
  #4 pmsrc/src/PocketMine(301): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[35] D:\Minecraft\Pocketmine-WorldEdits\, string[43] D:\Minecraft\Pocketmine-WorldEdits\plugins\)
  #5 pmsrc/src/PocketMine(324): pocketmine\server()
  #6 pmsrc(11): require(string[79] phar://D:/Minecraft/Pocketmine-WorldEdits/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by ItsZodiaX** [comment]
https://poggit.pmmp.io/p/blocklagfix download the plugin from here, should fix your issue
