### ISSUE TITLE
this plugin error ;-;

### ISSUE THREAD

**Issue by ItsJohnny30** [JavierLeon9966/BlockLagFix#8]
The plug-in will load with errors

**Comment by JavierLeon9966** [comment]
I don’t know what errors you are talking about since it loads fine for me. Could you send the crash dump here please

**Comment by ItsJohnny30** [comment]
> I don’t know what errors you are talking about since it loads fine for me. Could you send the crash dump here please

ok

**Comment by JavierLeon9966** [comment]
Well, I still don't see the crash dump

**Comment by JavierLeon9966** [comment]
The plugin works fine for me, so I think the problem is that you used an older version in which the startup crash wasn't fixed
